
      #########.
     ########",#:
   #########',##".
  ##'##'## .##',##.
   ## ## ## # ##",#.
    ## ## ## ## ##'
     ## ## ## :##
      ## ## ##."

version: 2

defaults: &defaults
  working_directory:
    &working_directory ~/typebolt
  docker:
    - image: circleci/node:9.7.1

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependencies-cache-{{ checksum "package.json" }}
          paths: [node_modules]
      - run: yarn test

  deploy:
    <<: *defaults
    steps:
      - attach_workspace: { at: *working_directory }
      - run:
          name: NPM Authentication
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/typebolt/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
          requires: [test]
          filters: { branches: { only: master } }
